print("Hello M.6/11")
print("My name is Kanitnan")
print("No.34")
print("age :",17,"years")
print("My birthday is 4 march 2548")
print("I sutdy at Chonrasadornmrung")
print("I'm from Thailand")
print("I live in Chonburi")
print("My hobby is waching movie")
print("I like nct")
#Kanitnan Audomlaaiad M.6/11